
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import java.awt.CardLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
public class mgusers extends javax.swing.JFrame {

    private static String filepath = "src\\netnexus.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray users = new JSONArray();

    public mgusers() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddBttn = new javax.swing.JButton();
        EdtBttn = new javax.swing.JButton();
        SrchBttn = new javax.swing.JButton();
        DltBttn = new javax.swing.JButton();
        backbtn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addpnl = new javax.swing.JPanel();
        AddUsnTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddPssTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddBlncTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AddLoginDteTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vipcmb = new javax.swing.JComboBox<>();
        addbtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        addtimeTF = new javax.swing.JTextField();
        editpnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EdtUsnTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EdtNewUsnTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EdtBlncTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EdtCb = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        EdtPssTF = new javax.swing.JTextField();
        NewLogDtTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        SveBttn = new javax.swing.JButton();
        deletepnl = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        DltTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        UserDltBttn = new javax.swing.JButton();
        searchpnl = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SrchTF = new javax.swing.JTextField();
        SrchUserBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        AddBttn.setText("Add User");
        AddBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBttnActionPerformed(evt);
            }
        });

        EdtBttn.setText("Edit User");
        EdtBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtBttnActionPerformed(evt);
            }
        });

        SrchBttn.setText("Search User");
        SrchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchBttnActionPerformed(evt);
            }
        });

        DltBttn.setText("Delete User");
        DltBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltBttnActionPerformed(evt);
            }
        });

        backbtn1.setText("Back");
        backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DltBttn)
                            .addComponent(SrchBttn)
                            .addComponent(EdtBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(AddBttn)
                .addGap(18, 18, 18)
                .addComponent(EdtBttn)
                .addGap(18, 18, 18)
                .addComponent(SrchBttn)
                .addGap(18, 18, 18)
                .addComponent(DltBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        addpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddUsnTF.setText("Enter Username");
        AddUsnTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUsnTFMouseClicked(evt);
            }
        });
        AddUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUsnTFActionPerformed(evt);
            }
        });
        addpnl.add(AddUsnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 127, 171, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Add User");
        addpnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 50, -1, -1));

        jLabel2.setText("Username");
        addpnl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 105, -1, -1));

        jLabel3.setText("Password:");
        addpnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 105, -1, -1));

        AddPssTF.setText("Enter Password");
        AddPssTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPssTFMouseClicked(evt);
            }
        });
        addpnl.add(AddPssTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 127, 171, -1));

        jLabel4.setText("Balance:");
        addpnl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        AddBlncTF.setText("0.0");
        AddBlncTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBlncTFMouseClicked(evt);
            }
        });
        AddBlncTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBlncTFActionPerformed(evt);
            }
        });
        addpnl.add(AddBlncTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 128, -1));

        jLabel5.setText("Login Date:");
        addpnl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 167, -1, -1));

        AddLoginDteTF.setText("mm-dd-yyyy");
        AddLoginDteTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLoginDteTFMouseClicked(evt);
            }
        });
        addpnl.add(AddLoginDteTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 189, 141, -1));

        jLabel6.setText("VIP Status:");
        addpnl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 67, 24));

        vipcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bronze", "Silver", "Gold" }));
        addpnl.add(vipcmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 92, -1));

        addbtn.setText("Add");
        addpnl.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel18.setText("Time Session:");
        addpnl.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        addtimeTF.setText("00:00:00");
        addtimeTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtimeTFMouseClicked(evt);
            }
        });
        addtimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtimeTFActionPerformed(evt);
            }
        });
        addpnl.add(addtimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jPanel2.add(addpnl, "card1");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Edit User");

        jLabel8.setText("Search Username:");

        EdtUsnTF.setText("Type Username");
        EdtUsnTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtUsnTFMouseClicked(evt);
            }
        });
        EdtUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtUsnTFActionPerformed(evt);
            }
        });

        jLabel9.setText("Edit Username:");

        EdtNewUsnTF.setText("Enter New Username");
        EdtNewUsnTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtNewUsnTFMouseClicked(evt);
            }
        });
        EdtNewUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtNewUsnTFActionPerformed(evt);
            }
        });

        jLabel10.setText("Balance:");

        EdtBlncTF.setText("0.0");
        EdtBlncTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtBlncTFMouseClicked(evt);
            }
        });
        EdtBlncTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtBlncTFActionPerformed(evt);
            }
        });

        jLabel11.setText("VIP Status:");

        EdtCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bronze", "Silver", "Gold" }));

        jLabel16.setText("New Password:");

        EdtPssTF.setText("Type Password");
        EdtPssTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtPssTFMouseClicked(evt);
            }
        });
        EdtPssTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtPssTFActionPerformed(evt);
            }
        });

        NewLogDtTF.setText("mm-dd-yyyy");
        NewLogDtTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewLogDtTFMouseClicked(evt);
            }
        });
        NewLogDtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewLogDtTFActionPerformed(evt);
            }
        });

        jLabel17.setText("New Login Date:");

        SveBttn.setText("Save ");

        javax.swing.GroupLayout editpnlLayout = new javax.swing.GroupLayout(editpnl);
        editpnl.setLayout(editpnlLayout);
        editpnlLayout.setHorizontalGroup(
            editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editpnlLayout.createSequentialGroup()
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editpnlLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editpnlLayout.createSequentialGroup()
                                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(EdtUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdtNewUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16)
                                    .addComponent(EdtPssTF, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(NewLogDtTF)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editpnlLayout.createSequentialGroup()
                                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(editpnlLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EdtCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EdtBlncTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SveBttn)
                                .addGap(42, 42, 42))))
                    .addGroup(editpnlLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel7)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        editpnlLayout.setVerticalGroup(
            editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editpnlLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdtPssTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtNewUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewLogDtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EdtBlncTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(SveBttn))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel2.add(editpnl, "card2");
        editpnl.getAccessibleContext().setAccessibleDescription("");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Delete User");

        DltTF.setText("Enter Username to Delete");
        DltTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DltTFMouseClicked(evt);
            }
        });

        jLabel13.setText("Username:");

        UserDltBttn.setText("Delete");

        javax.swing.GroupLayout deletepnlLayout = new javax.swing.GroupLayout(deletepnl);
        deletepnl.setLayout(deletepnlLayout);
        deletepnlLayout.setHorizontalGroup(
            deletepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(163, 163, 163))
            .addGroup(deletepnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DltTF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(deletepnlLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel13)
                .addContainerGap(265, Short.MAX_VALUE))
            .addGroup(deletepnlLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(UserDltBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletepnlLayout.setVerticalGroup(
            deletepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepnlLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel12)
                .addGap(50, 50, 50)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DltTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(UserDltBttn)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jPanel2.add(deletepnl, "card4");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Search User");

        jLabel15.setText("Username:");

        SrchTF.setText("Enter Username to Delete");
        SrchTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SrchTFMouseClicked(evt);
            }
        });
        SrchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchTFActionPerformed(evt);
            }
        });

        SrchUserBttn.setText("Search");
        SrchUserBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchUserBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchpnlLayout = new javax.swing.GroupLayout(searchpnl);
        searchpnl.setLayout(searchpnlLayout);
        searchpnlLayout.setHorizontalGroup(
            searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchpnlLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(171, 171, 171))
            .addGroup(searchpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SrchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(searchpnlLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(SrchUserBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchpnlLayout.setVerticalGroup(
            searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpnlLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel14)
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SrchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(SrchUserBttn)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jPanel2.add(searchpnl, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void AddBttnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card1");
    }                                       

    private void EdtUsnTFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    // TODO add your handling code here:

    private void EdtNewUsnTFActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void EdtBlncTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void AddUsnTFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        AddUsnTF.setText("");
    }                                        

    private void EdtBttnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card2");
    }                                       

    private void DltBttnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card4");
    }                                       

    private void SrchBttnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card3");
    }                                        

    private void EdtPssTFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    // TODO add your handling code here:

    private void NewLogDtTFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void SrchTFActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void SrchUserBttnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try {
            filecheck(); // Load or prepare your JSON file

            String usernameToSearch = SrchTF.getText().trim(); // Get username from text field
            boolean found = false;

            for (int i = 0; i < users.size(); i++) {
                JSONObject user = (JSONObject) users.get(i);
                if (user.get("username").equals(usernameToSearch)) {
                    found = true;

                    // Display user details
                    String userInfo = "Username: " + user.get("username")
                            + "\nPassword: " + user.get("password")
                            + "\nBalance: " + user.get("amount")
                            + "\nUsertime: " + user.get("userTime")
                            + "\nLogins: " + user.get("logins")
                            + "\nVIP Status: " + user.get("VipStatus");
                    JOptionPane.showMessageDialog(null, userInfo);
                    break;
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(null, "User not found.");
            }

        } catch (IOException | ParseException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }                                            

    private void backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

    }                                        

    private void SrchClrBttnActionPerformed(java.awt.event.ActionEvent evt) {                                            

    }                                           

    private void UserDltBttnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        try { // Check for any necessary file operations or preparations before adding data
            filecheck();

            String usernameToDelete = DltTF.getText();
            boolean found = false; // Flag to check if the user is found and deleted

            for (int i = 0; i < users.size(); i++) { // Loop through the userlist to search for the user by username
                JSONObject user = (JSONObject) users.get(i);
                if (user.get("username").equals(usernameToDelete)) {
                    users.remove(i); // Remove the user from the list
                    found = true; // Set found to true to indicate the user was found and deleted
                    break; // Exit the loop since the user is deleted
                }
            }

            if (found) {  // If the user was found and deleted, update the record and show message
                record.put("users", users); // Update the 'record' with the modified userlist
                JOptionPane.showMessageDialog(null, "Successfully deleted.");
            } else {
                JOptionPane.showMessageDialog(null, "User not found.");
            }
            save(); // Save the updated user list to the storage 

        } catch (IOException | ParseException ex) { // Catch any IOExceptions that may occur during file operations and log the error
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Catch any ParseExceptions that may occur during data processing


    }                                           

    private void SveBttnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            filecheck();

            String usernameToSearch = EdtUsnTF.getText().trim();
            String newUsername = EdtNewUsnTF.getText().trim();
            String newPassword = EdtPssTF.getText().trim();
            String newBalanceStr = EdtBlncTF.getText().trim();
            double newBalance = Double.parseDouble(newBalanceStr);
            String newLoginDate = NewLogDtTF.getText().trim();
            String newVip = EdtCb.getSelectedItem().toString();

            int timeInMinutes = (int) ((newBalance / 20) * 60);
            String formattedTime = formatTime(timeInMinutes);

            boolean found = false;
            for (int i = 0; i < users.size(); i++) {
                JSONObject user = (JSONObject) users.get(i);
                if (user.get("username").equals(usernameToSearch)) {
                    user.put("username", newUsername);
                    user.put("password", newPassword);
                    user.put("amount", newBalanceStr);
                    user.put("lastLogin", newLoginDate);
                    user.put("VipStatus", newVip);
                    user.put("userTime", formattedTime);
                    found = true;
                    break;
                }
            }

            if (found) {
                record.put("users", users);
                save();
                JOptionPane.showMessageDialog(null, "User updated successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "User not found.");
            }

        } catch (IOException | ParseException | NumberFormatException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error updating user. Please check input values.");
        }
    }                                       

    private void EdtClrBttnActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void EdtCbActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private String formatTime(int totalMinutes) {
        int hours = totalMinutes / 60;
        int minutes = totalMinutes % 60;
        return String.format("%02d:%02d:00", hours, minutes);
    }

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        try {
            filecheck();

            String username = AddUsnTF.getText().trim();
            String password = AddPssTF.getText().trim();
            String balanceStr = AddBlncTF.getText().trim();
            double balance = Double.parseDouble(balanceStr);
            String loginDate = AddLoginDteTF.getText().trim();
            String vipStatus = vipcmb.getSelectedItem().toString();

            // Check if user already exists
            for (Object obj : users) {
                JSONObject user = (JSONObject) obj;
                if (user.get("username").equals(username)) {
                    JOptionPane.showMessageDialog(null, "Username already exists!");
                    return;
                }
            }

            // Calculate time based on balance
            int timeInMinutes = (int) ((balance / 20) * 60); // 1 hour per 20 balance
            String formattedTime = formatTime(timeInMinutes);

            JSONObject newUser = new JSONObject();
            newUser.put("username", username);
            newUser.put("password", password);
            newUser.put("amount", balanceStr);
            newUser.put("userTime", formattedTime);
            newUser.put("lastLogin", loginDate);
            newUser.put("VipStatus", vipStatus);

            users.add(newUser);
            record.put("users", users);
            save();

            JOptionPane.showMessageDialog(null, "User added successfully!");

        } catch (IOException | ParseException | NumberFormatException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error adding user. Please check input values.");
        }

    }                                      

    private void DltClrBttnActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {                                       

    }                                      

    private void DltTFMouseClicked(java.awt.event.MouseEvent evt) {                                   
        DltTF.setText("");
    }                                  

    private void AddBlncTFActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }                                         

    private void AddUsnTFMouseClicked(java.awt.event.MouseEvent evt) {                                      
        AddUsnTF.setText("");
    }                                     

    private void AddPssTFMouseClicked(java.awt.event.MouseEvent evt) {                                      
        AddPssTF.setText("");    }                                     

    private void addtimeTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void AddBlncTFMouseClicked(java.awt.event.MouseEvent evt) {                                       
        AddBlncTF.setText("");
    }                                      

    private void AddLoginDteTFMouseClicked(java.awt.event.MouseEvent evt) {                                           
        AddLoginDteTF.setText("");
    }                                          

    private void addtimeTFMouseClicked(java.awt.event.MouseEvent evt) {                                       
        addtimeTF.setText("");
    }                                      

    private void EdtUsnTFMouseClicked(java.awt.event.MouseEvent evt) {                                      
        EdtUsnTF.setText("");
    }                                     

    private void EdtNewUsnTFMouseClicked(java.awt.event.MouseEvent evt) {                                         
        EdtNewUsnTF.setText(""); // TODO add your handling code here:
    }                                        

    private void EdtBlncTFMouseClicked(java.awt.event.MouseEvent evt) {                                       
        EdtBlncTF.setText("");        // TODO add your handling code here:
    }                                      

    private void EdtPssTFMouseClicked(java.awt.event.MouseEvent evt) {                                      
        EdtPssTF.setText("");        // TODO add your handling code here:
    }                                     

    private void NewLogDtTFMouseClicked(java.awt.event.MouseEvent evt) {                                        
        NewLogDtTF.setText("");        // TODO add your handling code here:
    }                                       

    private void SrchTFMouseClicked(java.awt.event.MouseEvent evt) {                                    
        SrchTF.setText("");        // TODO add your handling code here:
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mgusers().setVisible(true);
        });
    }

    public void filecheck() throws FileNotFoundException, IOException, ParseException {
        FileReader reader = new FileReader(filepath);

        if (reader.ready()) {
            Scanner scan = new Scanner(reader);
            String line = "";
            while (scan.hasNext()) {
                line = line + scan.nextLine();
            }

            reader.close();

            if (!line.equals("")) {
                reader.close();
                try (FileReader reader2 = new FileReader(filepath)) {
                    record = (JSONObject) jsonParser.parse(reader2);
                    users = (JSONArray) record.get("users");
                }
            }
        }
    }

    public static void save() throws IOException {
        try (FileWriter file = new FileWriter(filepath)) {
            file.write(record.toJSONString());
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField AddBlncTF;
    private javax.swing.JButton AddBttn;
    private javax.swing.JTextField AddLoginDteTF;
    private javax.swing.JTextField AddPssTF;
    private javax.swing.JTextField AddUsnTF;
    private javax.swing.JButton DltBttn;
    private javax.swing.JTextField DltTF;
    private javax.swing.JTextField EdtBlncTF;
    private javax.swing.JButton EdtBttn;
    private javax.swing.JComboBox<String> EdtCb;
    private javax.swing.JTextField EdtNewUsnTF;
    private javax.swing.JTextField EdtPssTF;
    private javax.swing.JTextField EdtUsnTF;
    private javax.swing.JTextField NewLogDtTF;
    private javax.swing.JButton SrchBttn;
    private javax.swing.JTextField SrchTF;
    private javax.swing.JButton SrchUserBttn;
    private javax.swing.JButton SveBttn;
    private javax.swing.JButton UserDltBttn;
    private javax.swing.JButton addbtn;
    private javax.swing.JPanel addpnl;
    private javax.swing.JTextField addtimeTF;
    private javax.swing.JButton backbtn1;
    private javax.swing.JPanel deletepnl;
    private javax.swing.JPanel editpnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel searchpnl;
    private javax.swing.JComboBox<String> vipcmb;
    // End of variables declaration                   
}
