
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import java.awt.CardLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
public class mgusers extends javax.swing.JFrame {

    private static String filepath = "src\\netnexus.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray users = new JSONArray();

    public mgusers() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddBttn = new javax.swing.JButton();
        EdtBttn = new javax.swing.JButton();
        SrchBttn = new javax.swing.JButton();
        DltBttn = new javax.swing.JButton();
        backbtn1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addpnl = new javax.swing.JPanel();
        AddUsnTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddPssTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddBlncTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AddLoginDteTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vipcmb = new javax.swing.JComboBox<>();
        clrbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        editpnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EdtUsnTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EdtNewUsnTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EdtBlncTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EdtCb = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        EdtPssTF = new javax.swing.JTextField();
        NewLogDtTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        EdtClrBttn = new javax.swing.JButton();
        SveBttn = new javax.swing.JButton();
        deletepnl = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        DltTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        DltClrBttn = new javax.swing.JButton();
        UserDltBttn = new javax.swing.JButton();
        searchpnl = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SrchTF = new javax.swing.JTextField();
        SrchClrBttn = new javax.swing.JButton();
        SrchUserBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(14, 14, 14));

        jPanel1.setBackground(new java.awt.Color(5, 5, 5));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        AddBttn.setBackground(new java.awt.Color(51, 51, 51));
        AddBttn.setForeground(new java.awt.Color(255, 255, 255));
        AddBttn.setText("Add User");
        AddBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBttnActionPerformed(evt);
            }
        });

        EdtBttn.setBackground(new java.awt.Color(51, 51, 51));
        EdtBttn.setForeground(new java.awt.Color(255, 255, 255));
        EdtBttn.setText("Edit User");
        EdtBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtBttnActionPerformed(evt);
            }
        });

        SrchBttn.setBackground(new java.awt.Color(51, 51, 51));
        SrchBttn.setForeground(new java.awt.Color(255, 255, 255));
        SrchBttn.setText("Search User");
        SrchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchBttnActionPerformed(evt);
            }
        });

        DltBttn.setBackground(new java.awt.Color(51, 51, 51));
        DltBttn.setForeground(new java.awt.Color(255, 255, 255));
        DltBttn.setText("Delete User");
        DltBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltBttnActionPerformed(evt);
            }
        });

        backbtn1.setBackground(new java.awt.Color(51, 51, 51));
        backbtn1.setForeground(new java.awt.Color(255, 255, 255));
        backbtn1.setText("Back");
        backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("NET");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("NEXUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DltBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(AddBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdtBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SrchBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(49, 49, 49)
                .addComponent(AddBttn)
                .addGap(18, 18, 18)
                .addComponent(EdtBttn)
                .addGap(18, 18, 18)
                .addComponent(SrchBttn)
                .addGap(18, 18, 18)
                .addComponent(DltBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        addpnl.setBackground(new java.awt.Color(14, 14, 14));

        AddUsnTF.setBackground(new java.awt.Color(51, 51, 51));
        AddUsnTF.setForeground(new java.awt.Color(255, 255, 255));
        AddUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUsnTFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add User");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        AddPssTF.setBackground(new java.awt.Color(51, 51, 51));
        AddPssTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Balance:");

        AddBlncTF.setBackground(new java.awt.Color(51, 51, 51));
        AddBlncTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login Date:");

        AddLoginDteTF.setBackground(new java.awt.Color(51, 51, 51));
        AddLoginDteTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VIP Status:");

        vipcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Bronze", "Silver", "Gold" }));

        clrbtn.setBackground(new java.awt.Color(255, 0, 0));
        clrbtn.setForeground(new java.awt.Color(255, 255, 255));
        clrbtn.setText("Clear");
        clrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbtnActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(56, 182, 255));
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addpnlLayout = new javax.swing.GroupLayout(addpnl);
        addpnl.setLayout(addpnlLayout);
        addpnlLayout.setHorizontalGroup(
            addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addpnlLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(AddUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(AddBlncTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addpnlLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vipcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AddPssTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(AddLoginDteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addpnlLayout.createSequentialGroup()
                        .addComponent(clrbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addbtn)))
                .addGap(21, 21, 21))
            .addGroup(addpnlLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addpnlLayout.setVerticalGroup(
            addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpnlLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPssTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBlncTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLoginDteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vipcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clrbtn)
                    .addComponent(addbtn))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel2.add(addpnl, "card1");

        editpnl.setBackground(new java.awt.Color(14, 14, 14));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edit User");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search Username:");

        EdtUsnTF.setBackground(new java.awt.Color(51, 51, 51));
        EdtUsnTF.setForeground(new java.awt.Color(255, 255, 255));
        EdtUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtUsnTFActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Edit Username:");

        EdtNewUsnTF.setBackground(new java.awt.Color(51, 51, 51));
        EdtNewUsnTF.setForeground(new java.awt.Color(255, 255, 255));
        EdtNewUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtNewUsnTFActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Balance:");

        EdtBlncTF.setBackground(new java.awt.Color(51, 51, 51));
        EdtBlncTF.setForeground(new java.awt.Color(255, 255, 255));
        EdtBlncTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtBlncTFActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("VIP Status:");

        EdtCb.setForeground(new java.awt.Color(255, 255, 255));
        EdtCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Bronze", "Silver", "Gold" }));
        EdtCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtCbActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("New Password:");

        EdtPssTF.setBackground(new java.awt.Color(51, 51, 51));
        EdtPssTF.setForeground(new java.awt.Color(255, 255, 255));
        EdtPssTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtPssTFActionPerformed(evt);
            }
        });

        NewLogDtTF.setBackground(new java.awt.Color(51, 51, 51));
        NewLogDtTF.setForeground(new java.awt.Color(255, 255, 255));
        NewLogDtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewLogDtTFActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("New Login Date:");

        EdtClrBttn.setBackground(new java.awt.Color(255, 0, 0));
        EdtClrBttn.setForeground(new java.awt.Color(255, 255, 255));
        EdtClrBttn.setText("Clear");
        EdtClrBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtClrBttnActionPerformed(evt);
            }
        });

        SveBttn.setBackground(new java.awt.Color(56, 182, 255));
        SveBttn.setForeground(new java.awt.Color(255, 255, 255));
        SveBttn.setText("Save ");
        SveBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SveBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editpnlLayout = new javax.swing.GroupLayout(editpnl);
        editpnl.setLayout(editpnlLayout);
        editpnlLayout.setHorizontalGroup(
            editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editpnlLayout.createSequentialGroup()
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editpnlLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editpnlLayout.createSequentialGroup()
                                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(EdtUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdtNewUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16)
                                    .addComponent(EdtPssTF, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(NewLogDtTF)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editpnlLayout.createSequentialGroup()
                                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(editpnlLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EdtCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EdtBlncTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(EdtClrBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SveBttn))))
                    .addGroup(editpnlLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel7)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        editpnlLayout.setVerticalGroup(
            editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editpnlLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdtPssTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtNewUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewLogDtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editpnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EdtBlncTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EdtCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(editpnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(editpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EdtClrBttn)
                            .addComponent(SveBttn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.add(editpnl, "card2");
        editpnl.getAccessibleContext().setAccessibleDescription("");

        deletepnl.setBackground(new java.awt.Color(14, 14, 14));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Delete User");

        DltTF.setBackground(new java.awt.Color(51, 51, 51));
        DltTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Username:");

        DltClrBttn.setBackground(new java.awt.Color(255, 0, 0));
        DltClrBttn.setForeground(new java.awt.Color(255, 255, 255));
        DltClrBttn.setText("Clear");
        DltClrBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltClrBttnActionPerformed(evt);
            }
        });

        UserDltBttn.setBackground(new java.awt.Color(153, 0, 0));
        UserDltBttn.setForeground(new java.awt.Color(255, 255, 255));
        UserDltBttn.setText("Delete");
        UserDltBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserDltBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletepnlLayout = new javax.swing.GroupLayout(deletepnl);
        deletepnl.setLayout(deletepnlLayout);
        deletepnlLayout.setHorizontalGroup(
            deletepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepnlLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(163, 163, 163))
            .addGroup(deletepnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deletepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(deletepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(deletepnlLayout.createSequentialGroup()
                            .addComponent(DltClrBttn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserDltBttn))
                        .addComponent(DltTF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletepnlLayout.setVerticalGroup(
            deletepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepnlLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel12)
                .addGap(50, 50, 50)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DltTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(deletepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserDltBttn)
                    .addComponent(DltClrBttn))
                .addGap(103, 103, 103))
        );

        jPanel2.add(deletepnl, "card4");

        searchpnl.setBackground(new java.awt.Color(14, 14, 14));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Search User");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Username:");

        SrchTF.setBackground(new java.awt.Color(51, 51, 51));
        SrchTF.setForeground(new java.awt.Color(255, 255, 255));
        SrchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchTFActionPerformed(evt);
            }
        });

        SrchClrBttn.setBackground(new java.awt.Color(255, 0, 0));
        SrchClrBttn.setForeground(new java.awt.Color(255, 255, 255));
        SrchClrBttn.setText("Clear");
        SrchClrBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchClrBttnActionPerformed(evt);
            }
        });

        SrchUserBttn.setBackground(new java.awt.Color(56, 182, 255));
        SrchUserBttn.setForeground(new java.awt.Color(255, 255, 255));
        SrchUserBttn.setText("Search");
        SrchUserBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchUserBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchpnlLayout = new javax.swing.GroupLayout(searchpnl);
        searchpnl.setLayout(searchpnlLayout);
        searchpnlLayout.setHorizontalGroup(
            searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchpnlLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(171, 171, 171))
            .addGroup(searchpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(searchpnlLayout.createSequentialGroup()
                            .addComponent(SrchClrBttn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SrchUserBttn))
                        .addComponent(SrchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchpnlLayout.setVerticalGroup(
            searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpnlLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel14)
                .addGroup(searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchpnlLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SrchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(searchpnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addGroup(searchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SrchClrBttn)
                            .addComponent(SrchUserBttn))
                        .addGap(108, 108, 108))))
        );

        jPanel2.add(searchpnl, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBttnActionPerformed
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card1");
    }//GEN-LAST:event_AddBttnActionPerformed

    private void EdtUsnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtUsnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtUsnTFActionPerformed

    private void EdtNewUsnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtNewUsnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtNewUsnTFActionPerformed

    private void EdtBlncTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtBlncTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtBlncTFActionPerformed

    private void AddUsnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUsnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUsnTFActionPerformed

    private void EdtBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtBttnActionPerformed
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card2");
    }//GEN-LAST:event_EdtBttnActionPerformed

    private void DltBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltBttnActionPerformed
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card4");
    }//GEN-LAST:event_DltBttnActionPerformed

    private void SrchBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrchBttnActionPerformed
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card3");
    }//GEN-LAST:event_SrchBttnActionPerformed

    private void EdtPssTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtPssTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtPssTFActionPerformed

    private void NewLogDtTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewLogDtTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewLogDtTFActionPerformed

    private void SrchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SrchTFActionPerformed

    private void SrchUserBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrchUserBttnActionPerformed
        try {
            filecheck(); // Load or prepare your JSON file

            String usernameToSearch = SrchTF.getText().trim(); // Get username from text field
            boolean found = false;

            for (int i = 0; i < users.size(); i++) {
                JSONObject user = (JSONObject) users.get(i);
                if (user.get("username").equals(usernameToSearch)) {
                    found = true;

                    // Display user details
                    String userInfo = "Username: " + user.get("username")
                            + "\nPassword: " + user.get("password")
                            + "\nBalance: " + user.get("amount")
                            + "\nUsertime: " + user.get("userTime")
                            + "\nLogins: " + user.get("logins")
                            + "\nVIP Status: " + user.get("VipStatus");
                    JOptionPane.showMessageDialog(null, userInfo);
                    break;
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(null, "User not found.");
            }

        } catch (IOException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SrchUserBttnActionPerformed

    private void backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn1ActionPerformed

    }//GEN-LAST:event_backbtn1ActionPerformed

    private void SrchClrBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrchClrBttnActionPerformed
        SrchTF.setText("");

    }//GEN-LAST:event_SrchClrBttnActionPerformed

    private void UserDltBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserDltBttnActionPerformed
        try { // Check for any necessary file operations or preparations before adding data
            filecheck();

            String usernameToDelete = DltTF.getText();
            boolean found = false; // Flag to check if the user is found and deleted

            for (int i = 0; i < users.size(); i++) { // Loop through the userlist to search for the user by username
                JSONObject user = (JSONObject) users.get(i);
                if (user.get("username").equals(usernameToDelete)) {
                    users.remove(i); // Remove the user from the list
                    found = true; // Set found to true to indicate the user was found and deleted
                    break; // Exit the loop since the user is deleted
                }
            }

            if (found) {  // If the user was found and deleted, update the record and show message
                record.put("users", users); // Update the 'record' with the modified userlist
                JOptionPane.showMessageDialog(null, "Successfully deleted.");
            } else {
                JOptionPane.showMessageDialog(null, "User not found.");
            }
            save(); // Save the updated user list to the storage 

        } catch (IOException ex) { // Catch any IOExceptions that may occur during file operations and log the error
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) { //Catch any ParseExceptions that may occur during data processing
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_UserDltBttnActionPerformed

    private void SveBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SveBttnActionPerformed
        try {
            filecheck();

            String usernameToSearch = EdtUsnTF.getText().trim();
            String newUsername = EdtNewUsnTF.getText().trim();
            String newPassword = EdtPssTF.getText().trim();
            String newBalanceStr = EdtBlncTF.getText().trim();
            double newBalance = Double.parseDouble(newBalanceStr);
            String newLoginDate = NewLogDtTF.getText().trim();
            String newVip = EdtCb.getSelectedItem().toString();

            int timeInMinutes = (int) ((newBalance / 20) * 60);
            String formattedTime = formatTime(timeInMinutes);

            boolean found = false;
            for (int i = 0; i < users.size(); i++) {
                JSONObject user = (JSONObject) users.get(i);
                if (user.get("username").equals(usernameToSearch)) {
                    user.put("username", newUsername);
                    user.put("password", newPassword);
                    user.put("amount", newBalanceStr);
                    user.put("lastLogin", newLoginDate);
                    user.put("VipStatus", newVip);
                    user.put("userTime", formattedTime);
                    found = true;
                    break;
                }
            }

            if (found) {
                record.put("users", users);
                save();
                JOptionPane.showMessageDialog(null, "User updated successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "User not found.");
            }

        } catch (IOException | ParseException | NumberFormatException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error updating user. Please check input values.");
        }
    }//GEN-LAST:event_SveBttnActionPerformed

    private void EdtClrBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtClrBttnActionPerformed
        EdtUsnTF.setText("");
        EdtNewUsnTF.setText("");
        EdtPssTF.setText("");
        EdtBlncTF.setText("");
        NewLogDtTF.setText("");
    }//GEN-LAST:event_EdtClrBttnActionPerformed

    private void EdtCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtCbActionPerformed

    private String formatTime(int totalMinutes) {
        int hours = totalMinutes / 60;
        int minutes = totalMinutes % 60;
        return String.format("%02d:%02d:00", hours, minutes);
    }

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {
            filecheck();

            String username = AddUsnTF.getText().trim();
            String password = AddPssTF.getText().trim();
            String balanceStr = AddBlncTF.getText().trim();
            double balance = Double.parseDouble(balanceStr);
            String loginDate = AddLoginDteTF.getText().trim();
            String vipStatus = vipcmb.getSelectedItem().toString();

            // Check if user already exists
            for (Object obj : users) {
                JSONObject user = (JSONObject) obj;
                if (user.get("username").equals(username)) {
                    JOptionPane.showMessageDialog(null, "Username already exists!");
                    return;
                }
            }

            // Calculate time based on balance
            int timeInMinutes = (int) ((balance / 20) * 60); // 1 hour per 20 balance
            String formattedTime = formatTime(timeInMinutes);

            JSONObject newUser = new JSONObject();
            newUser.put("username", username);
            newUser.put("password", password);
            newUser.put("amount", balanceStr);
            newUser.put("userTime", formattedTime);
            newUser.put("lastLogin", loginDate);
            newUser.put("VipStatus", vipStatus);

            users.add(newUser);
            record.put("users", users);
            save();

            JOptionPane.showMessageDialog(null, "User added successfully!");

        } catch (IOException | ParseException | NumberFormatException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error adding user. Please check input values.");
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void DltClrBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltClrBttnActionPerformed
        DltTF.setText("");
    }//GEN-LAST:event_DltClrBttnActionPerformed

    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtnActionPerformed
        AddUsnTF.setText("");
        AddPssTF.setText("");
        AddBlncTF.setText("");
        AddLoginDteTF.setText("");
    }//GEN-LAST:event_clrbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mgusers().setVisible(true);
            }
        });
    }

    public void filecheck() throws FileNotFoundException, IOException, ParseException {
        FileReader reader = new FileReader(filepath);

        if (reader.ready()) {
            Scanner scan = new Scanner(reader);
            String line = "";
            while (scan.hasNext()) {
                line = line + scan.nextLine();
            }

            reader.close();

            if (!line.equals("")) {
                reader.close();
                FileReader reader2 = new FileReader(filepath);
                record = (JSONObject) jsonParser.parse(reader2);
                users = (JSONArray) record.get("users");
                reader2.close();
            }
        }
    }

    public static void save() throws IOException {
        FileWriter file = new FileWriter(filepath);
        file.write(record.toJSONString());
        file.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddBlncTF;
    private javax.swing.JButton AddBttn;
    private javax.swing.JTextField AddLoginDteTF;
    private javax.swing.JTextField AddPssTF;
    private javax.swing.JTextField AddUsnTF;
    private javax.swing.JButton DltBttn;
    private javax.swing.JButton DltClrBttn;
    private javax.swing.JTextField DltTF;
    private javax.swing.JTextField EdtBlncTF;
    private javax.swing.JButton EdtBttn;
    private javax.swing.JComboBox<String> EdtCb;
    private javax.swing.JButton EdtClrBttn;
    private javax.swing.JTextField EdtNewUsnTF;
    private javax.swing.JTextField EdtPssTF;
    private javax.swing.JTextField EdtUsnTF;
    private javax.swing.JTextField NewLogDtTF;
    private javax.swing.JButton SrchBttn;
    private javax.swing.JButton SrchClrBttn;
    private javax.swing.JTextField SrchTF;
    private javax.swing.JButton SrchUserBttn;
    private javax.swing.JButton SveBttn;
    private javax.swing.JButton UserDltBttn;
    private javax.swing.JButton addbtn;
    private javax.swing.JPanel addpnl;
    private javax.swing.JButton backbtn1;
    private javax.swing.JButton clrbtn;
    private javax.swing.JPanel deletepnl;
    private javax.swing.JPanel editpnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel searchpnl;
    private javax.swing.JComboBox<String> vipcmb;
    // End of variables declaration//GEN-END:variables
}
